import type { Metadata } from "next";
import "./globals.css";
import React from "react";

import Providers from "@front/providers";
import Header from "@front/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko" className="h-full">
      <body className="antialiased">
        <Providers>
          <Header></Header>
        <main className="container mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;