import type { Metadata } from "next";
import "./globals.css";
import React from "react";

import Providers from "@front/providers";
import Header from "@front/components/RootLayout/Header";
import Footer from "@front/components/RootLayout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko" className="h-full">
      <body className="antialiased">
        <Providers>
          <Header></Header>
          <main className="w-full h-full">{children}</main>
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;